package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import modelo.MySQL;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Conexion;
import modelo.Docente;
import modelo.MD5;
import modelo.SqlAlumno;
import modelo.SqlDocente;

public class Admin extends javax.swing.JFrame {

    MySQL db = new MySQL();
    
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        disableField();
        db.MySQLConnection("root", "", "Escuela");
        DefaultTableModel modelo = new DefaultTableModel();
            jtAlumnos.setModel(modelo);
            modelo.setRowCount(0);
            
            ImageIcon logo = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo grande.jpg")));
            Image img1 = logo.getImage();
            Image img2 = img1.getScaledInstance(jf_logo.getWidth(), jf_logo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon i = new ImageIcon(img2);
            
            jf_logo.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        alu_Clave = new javax.swing.JTextField();
        alu_Nacimiento = new com.toedter.calendar.JDateChooser();
        btn_RegAlumno = new javax.swing.JButton();
        btn_CanAlumno = new javax.swing.JButton();
        alu_Nombre = new javax.swing.JTextField();
        alu_Sapellido = new javax.swing.JTextField();
        alu_Domicilio = new javax.swing.JTextField();
        alu_Tel = new javax.swing.JTextField();
        alu_Correo = new javax.swing.JTextField();
        alu_Papellido = new javax.swing.JTextField();
        alu_Password = new javax.swing.JPasswordField();
        alu_Spassword = new javax.swing.JPasswordField();
        jB_Limpiar = new javax.swing.JButton();
        alu_Semestre = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        doc_Clave = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        doc_Nombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        doc_Papellido = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        doc_Sapellido = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        doc_Nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        doc_Domicilio = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        doc_Telefono = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        doc_Correo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        doc_Password = new javax.swing.JPasswordField();
        btn_CanDocente = new javax.swing.JButton();
        btn_RegDocente = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        doc_Spassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnTModificar = new javax.swing.JButton();
        label_TClave = new javax.swing.JLabel();
        alu_TClave = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        alu_TNombre = new javax.swing.JTextField();
        alu_TPapellido = new javax.swing.JTextField();
        alu_TSapellido = new javax.swing.JTextField();
        alu_TNacimiento = new javax.swing.JTextField();
        alu_TDomicilio = new javax.swing.JTextField();
        alu_TTelefono = new javax.swing.JTextField();
        alu_TCorreo = new javax.swing.JTextField();
        btnTEliminar = new javax.swing.JButton();
        btnTBuscar = new javax.swing.JButton();
        alu_TSemestre = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jB_Limpiar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDocente = new javax.swing.JTable();
        btn_ADocente = new javax.swing.JButton();
        label_TClave1 = new javax.swing.JLabel();
        doc_TClave = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        doc_TNombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        doc_TPapellido = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        doc_TSapellido = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        doc_TNacimiento = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        doc_TDomicilio = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        doc_TTelefono = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        doc_TCorreo = new javax.swing.JTextField();
        btnTDBuscar = new javax.swing.JButton();
        btnTDModificar = new javax.swing.JButton();
        btnTDEliminar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jf_logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Alumno");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Clave:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Primer Apellido:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Segundo Apellido:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de nacimiento:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Domicilio:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Correo:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Nueva contraseña:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Vuelva a escribir la contraseña:");

        alu_Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_ClaveActionPerformed(evt);
            }
        });
        alu_Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_ClaveKeyTyped(evt);
            }
        });

        alu_Nacimiento.setDateFormatString("yyyy-MM-d");

        btn_RegAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_RegAlumno.setText("Registrar");
        btn_RegAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegAlumnoActionPerformed(evt);
            }
        });

        btn_CanAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_CanAlumno.setText("Cerrar");
        btn_CanAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CanAlumnoActionPerformed(evt);
            }
        });

        alu_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_NombreActionPerformed(evt);
            }
        });
        alu_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_NombreKeyTyped(evt);
            }
        });

        alu_Sapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_SapellidoActionPerformed(evt);
            }
        });
        alu_Sapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_SapellidoKeyTyped(evt);
            }
        });

        alu_Domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_DomicilioActionPerformed(evt);
            }
        });
        alu_Domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_DomicilioKeyTyped(evt);
            }
        });

        alu_Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_TelActionPerformed(evt);
            }
        });
        alu_Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_TelKeyTyped(evt);
            }
        });

        alu_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_CorreoActionPerformed(evt);
            }
        });
        alu_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_CorreoKeyTyped(evt);
            }
        });

        alu_Papellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_PapellidoActionPerformed(evt);
            }
        });
        alu_Papellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_PapellidoKeyTyped(evt);
            }
        });

        alu_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_PasswordKeyTyped(evt);
            }
        });

        jB_Limpiar.setText("Limpiar");
        jB_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LimpiarActionPerformed(evt);
            }
        });

        alu_Semestre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_SemestreKeyTyped(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel38.setText("Semestre:");

        jLabel39.setText("YYYY-MM-DD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(25, 25, 25)
                                .addComponent(alu_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alu_Papellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alu_Sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel38))
                                .addGap(120, 120, 120)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alu_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alu_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alu_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alu_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alu_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(132, 132, 132)
                                .addComponent(alu_Password))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(33, 33, 33)
                                .addComponent(alu_Spassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(277, 277, 277))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btn_CanAlumno)
                                .addGap(19, 19, 19)
                                .addComponent(jB_Limpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_RegAlumno))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alu_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alu_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(alu_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alu_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(alu_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alu_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(alu_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(alu_Papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(alu_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alu_Sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(alu_Spassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39))
                    .addComponent(alu_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CanAlumno)
                    .addComponent(jB_Limpiar)
                    .addComponent(btn_RegAlumno))
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Registro Alumno", jPanel1);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("Registro de Docente");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Clave:");

        doc_Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_ClaveActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Nombre:");

        doc_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_NombreActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Primer Apellido:");

        doc_Papellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_PapellidoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Segundo Apellido:");

        doc_Sapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_SapellidoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Fecha de nacimiento:");

        doc_Nacimiento.setDateFormatString("yyyy-MM-d");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Domicilio:");

        doc_Domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_DomicilioActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Teléfono:");

        doc_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_TelefonoActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Correo:");

        doc_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_CorreoActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Nueva contraseña:");

        btn_CanDocente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_CanDocente.setText("Cancelar");
        btn_CanDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CanDocenteActionPerformed(evt);
            }
        });

        btn_RegDocente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_RegDocente.setText("Registrar");
        btn_RegDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegDocenteActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Vuelva a escribir la contraseña:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addGap(23, 23, 23)
                        .addComponent(doc_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(doc_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(doc_Password)
                                        .addComponent(doc_Sapellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(doc_Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(doc_Telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(doc_Correo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(doc_Domicilio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(doc_Papellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btn_CanDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_RegDocente)))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doc_Spassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(695, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(doc_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doc_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(doc_Papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(doc_Sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(doc_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(doc_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(doc_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doc_Spassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(doc_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doc_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CanDocente)
                    .addComponent(btn_RegDocente))
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Registro Docente", jPanel2);

        jtAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Semestre", "Nombre", "Apellido Paterno", "Apellido Materno", "Fecha de Nacimiento", "Dirección", "Teléfono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlumnos);

        jButton1.setText("Ver Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTModificar.setText("Modificar");
        btnTModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTModificarActionPerformed(evt);
            }
        });

        label_TClave.setText("Clave");

        alu_TClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_TClaveKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Correo:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Teléfono:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Domicilio:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Fecha de nacimiento:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Segundo Apellido:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Primer Apellido:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Nombre:");

        alu_TTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alu_TTelefonoKeyTyped(evt);
            }
        });

        alu_TCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_TCorreoActionPerformed(evt);
            }
        });

        btnTEliminar.setText("Eliminar");
        btnTEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTEliminarActionPerformed(evt);
            }
        });

        btnTBuscar.setText("Buscar");
        btnTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTBuscarActionPerformed(evt);
            }
        });

        alu_TSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alu_TSemestreActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setText("Semestre:");

        jB_Limpiar1.setText("Limpiar");
        jB_Limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Limpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(label_TClave)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alu_TClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alu_TSapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alu_TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alu_TPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37)
                                .addGap(44, 44, 44)
                                .addComponent(alu_TSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(317, 317, 317))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(122, 122, 122)
                                        .addComponent(alu_TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alu_TNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alu_TDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(110, 110, 110)
                                .addComponent(alu_TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(734, 734, 734))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnTEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnTModificar)
                        .addGap(60, 60, 60)
                        .addComponent(jB_Limpiar1)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnTBuscar)
                    .addComponent(btnTModificar)
                    .addComponent(btnTEliminar)
                    .addComponent(jB_Limpiar1))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(alu_TNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_TClave, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alu_TClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alu_TSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(alu_TDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(alu_TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(alu_TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(alu_TPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(alu_TSapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(alu_TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Alumnos", jPanel3);

        jtDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Apellido Paterno", "Apellido Materno", "Fecha de Nacimiento", "Dirección", "Teléfono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDocenteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtDocente);

        btn_ADocente.setText("Actualizar");
        btn_ADocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ADocenteActionPerformed(evt);
            }
        });

        label_TClave1.setText("Clave");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Nombre:");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Primer Apellido:");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Segundo Apellido:");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Fecha de nacimiento:");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("Domicilio:");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Teléfono:");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setText("Correo:");

        doc_TCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_TCorreoActionPerformed(evt);
            }
        });

        btnTDBuscar.setText("Buscar");
        btnTDBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDBuscarActionPerformed(evt);
            }
        });

        btnTDModificar.setText("Modificar");
        btnTDModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDModificarActionPerformed(evt);
            }
        });

        btnTDEliminar.setText("Eliminar");
        btnTDEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ADocente)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(label_TClave1))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doc_TClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_TSapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_TPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doc_TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(doc_TDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(110, 110, 110)
                                        .addComponent(doc_TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(doc_TNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel34))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTDModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTDEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTDBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ADocente)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(doc_TNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_TClave1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc_TClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(doc_TDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTDBuscar))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(doc_TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTDModificar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doc_TCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTDEliminar)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(doc_TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(doc_TPapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(doc_TSapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta de Docentes", jPanel4);

        jf_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jf_logo.setMaximumSize(new java.awt.Dimension(1366, 73));
        jf_logo.setMinimumSize(new java.awt.Dimension(1366, 73));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alu_ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_ClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_ClaveActionPerformed

    private void alu_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_NombreActionPerformed

    private void alu_SapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_SapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_SapellidoActionPerformed

    private void alu_DomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_DomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_DomicilioActionPerformed

    private void alu_TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_TelActionPerformed

    private void alu_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_CorreoActionPerformed

    private void alu_PapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_PapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_PapellidoActionPerformed

    private void btn_RegAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegAlumnoActionPerformed
        SqlAlumno modSql = new SqlAlumno();
        Alumno alum = new Alumno();
        
        String pass = new String(alu_Password.getPassword());
        String passCon = new String(alu_Spassword.getPassword());
        
        if ("".equals(alu_Clave.getText()) ||"".equals(alu_Nombre.getText()) || 
            "".equals(alu_Papellido.getText()) || 
            "".equals(alu_Domicilio.getText()) || "".equals(alu_Tel.getText()) || 
            "".equals(alu_Correo.getText()) || alu_Nacimiento.getDate()==null){
            JOptionPane.showMessageDialog(null, "Verifique que todos los campos"
                    + " esten correctos.");
        }else{
            if(pass.equals(passCon)){
                SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");

                String nuevoPass = MD5.getHash(pass);

                alum.setId(Integer.parseInt(alu_Clave.getText()));
                alum.setNombre(alu_Nombre.getText());
                alum.setApe_Paterno(alu_Papellido.getText());
                alum.setApe_Materno(alu_Sapellido.getText());
                alum.setFechaNacimiento(Date_Format.format(alu_Nacimiento.getDate()));
                alum.setDireccion(alu_Domicilio.getText());
                alum.setTelefono(alu_Tel.getText());
                alum.setCorreo(alu_Correo.getText());
                alum.setContrasena(nuevoPass);
                alum.setSemestre(Integer.parseInt(alu_Semestre.getText()));
                if (modSql.registrar(alum)){
                    JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO");
                    limpiarFields();
                }else
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error, "
                            + "comprueba que los datos esten correctos.");
            }else{
                JOptionPane.showMessageDialog(null, "No coinciden las contraseñas");
            }
        }
    }//GEN-LAST:event_btn_RegAlumnoActionPerformed

    private void btn_CanAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CanAlumnoActionPerformed
        // TODO add your handling code here:
        db.closeConnection();
        this.dispose();
    }//GEN-LAST:event_btn_CanAlumnoActionPerformed

    void disableField(){
        alu_TNacimiento.setEnabled(false);
        alu_TNombre.setEnabled(false);
        alu_TPapellido.setEnabled(false);
        alu_TSapellido.setEnabled(false);
        alu_TCorreo.setEnabled(false);
        alu_TTelefono.setEnabled(false);
        alu_TSemestre.setEnabled(false);
        alu_TDomicilio.setEnabled(false);
    }
    
    void activeField(){
        alu_TNacimiento.setEnabled(true);
        alu_TNombre.setEnabled(true);
        alu_TPapellido.setEnabled(true);
        alu_TSapellido.setEnabled(true);
        alu_TCorreo.setEnabled(true);
        alu_TTelefono.setEnabled(true);
        alu_TSemestre.setEnabled(true);
        alu_TDomicilio.setEnabled(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String campo = alu_TClave.getText();
                
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jtAlumnos.setModel(modelo);
            
            PreparedStatement ps;
            ResultSet rs;
            Conexion conn= new Conexion();
            Connection con = conn.getConexion();
            
            String sql ="SELECT idAlumno, semestre, nombre, ape_paterno, ape_materno, "
                    +"fechaNacimiento, direccion, telefono, correo FROM Alumno";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Clave");
            modelo.addColumn("Semestre");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Fecha de Nacimiento");
            modelo.addColumn("Dirección");
            modelo.addColumn("Teléfono");
            modelo.addColumn("Correo");
            
            int[] anchos = {40,5,80,70,70,60,130,50,90};
            for(int x=0; x< cantidadColumnas; x++)
                jtAlumnos.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0;i < cantidadColumnas; i++){
                    filas[i]= rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Se encontro un error y no es "
                    + "posible mostrar la información");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlumnosMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion conn= new Conexion();
            Connection con = conn.getConexion();
            
            int fila =jtAlumnos.getSelectedRow();
            String codigo = jtAlumnos.getValueAt(fila, 0).toString();
            
            ps = con.prepareStatement("SELECT idAlumno, nombre, ape_paterno, "
                    + "ape_materno, fechaNacimiento, direccion, telefono, "
                    + "correo, semestre FROM Alumno WHERE idAlumno=?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();
            
            while(rs.next()){
                activeField();
                alu_TClave.setText(rs.getString("idAlumno"));
                alu_TNombre.setText(rs.getString("nombre"));
                alu_TPapellido.setText(rs.getString("ape_paterno"));
                alu_TSapellido.setText(rs.getString("ape_materno"));
                alu_TNacimiento.setText(rs.getString("fechaNacimiento"));
                alu_TDomicilio.setText(rs.getString("direccion"));
                alu_TTelefono.setText(rs.getString("telefono"));
                alu_TCorreo.setText(rs.getString("correo"));
                alu_TSemestre.setText(rs.getString("semestre"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ha ocurrido un error inesperado");
        }
    }//GEN-LAST:event_jtAlumnosMouseClicked

    private void alu_TCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_TCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_TCorreoActionPerformed

    void limpiarFields(){
        alu_TClave.setText("");
        alu_TNombre.setText("");
        alu_TPapellido.setText("");
        alu_TSapellido.setText("");
        alu_TNacimiento.setText("");
        alu_TDomicilio.setText("");
        alu_TTelefono.setText("");
        alu_TCorreo.setText("");
        alu_TSemestre.setText("");
        alu_Clave.setText("");
        alu_Nombre.setText("");
        alu_Papellido.setText("");
        alu_Sapellido.setText("");
        alu_Nacimiento.setCalendar(null);
        alu_Domicilio.setText("");
        alu_Tel.setText("");
        alu_Correo.setText("");
        alu_Password.setText("");
        alu_Spassword.setText("");
        alu_Semestre.setText("");
        
        doc_TClave.setText("");
        doc_TNombre.setText("");
        doc_TPapellido.setText("");
        doc_TSapellido.setText("");
        doc_TNacimiento.setText("");
        doc_TDomicilio.setText("");
        doc_TTelefono.setText("");
        doc_TCorreo.setText("");
        doc_Clave.setText("");
        doc_Nombre.setText("");
        doc_Papellido.setText("");
        doc_Sapellido.setText("");
        //alu_Nacimiento.setDate("1999-10-1");
        doc_Domicilio.setText("");
        doc_Telefono.setText("");
        doc_Correo.setText("");
        doc_Password.setText("");
        doc_Spassword.setText("");
    }
    
    
    
    private void btnTEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTEliminarActionPerformed
        
        PreparedStatement ps = null;
        try {
            Conexion conn= new Conexion();
            Connection con = conn.getConexion();
            if (jtAlumnos.getSelectedRow()>-1){
                int fila =jtAlumnos.getSelectedRow();
                String codigo = jtAlumnos.getValueAt(fila, 0).toString();

                ps = con.prepareStatement("DELETE FROM Alumno WHERE idAlumno=?");
                ps.setString(1, codigo);
                ps.execute();
                limpiarFields();
                JOptionPane.showMessageDialog(null, "Se ha eliminado "
                        + "el registro.");
                disableField();
            }else{
                JOptionPane.showMessageDialog(null, "No ha sido posible eliminar "
                    + "el registro.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No ha sido posible eliminar "
                    + "el registro.");
        }
    }//GEN-LAST:event_btnTEliminarActionPerformed

    private void btnTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTBuscarActionPerformed
        String campo = alu_TClave.getText();
        String where ="";
        
        if(!"".equals(campo)){
            where = "WHERE idAlumno = '"+campo+"'";
            try {
                DefaultTableModel modelo = new DefaultTableModel();
                jtAlumnos.setModel(modelo);

                PreparedStatement ps = null;
                ResultSet rs = null;
                Conexion conn= new Conexion();
                Connection con = conn.getConexion();

                String sql ="SELECT idAlumno, nombre, semestre, ape_paterno, ape_materno, "
                        +"fechaNacimiento, direccion, telefono, correo FROM Alumno "
                        + where;
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();

                ResultSetMetaData rsMd = rs.getMetaData();
                int cantidadColumnas = rsMd.getColumnCount();

                modelo.addColumn("Clave");
                modelo.addColumn("Nombre");
                modelo.addColumn("Semestre");
                modelo.addColumn("Apellido Paterno");
                modelo.addColumn("Apellido Materno");
                modelo.addColumn("Fecha de Nacimiento");
                modelo.addColumn("Dirección");
                modelo.addColumn("Teléfono");
                modelo.addColumn("Correo");

                int[] anchos = {40,5,80,70,70,60,130,50,90};
                for(int x=0; x< cantidadColumnas; x++)
                    jtAlumnos.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);

                while(rs.next()){
                    Object[] filas = new Object[cantidadColumnas];

                    for(int i=0;i < cantidadColumnas; i++){
                        filas[i]= rs.getObject(i+1);
                    }
                    modelo.addRow(filas);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Se encontro un error y no es "
                        + "posible mostrar la información");
            }
        }else JOptionPane.showMessageDialog(null, "Ingresa la clave para Buscar");
        
    }//GEN-LAST:event_btnTBuscarActionPerformed

    private void btnTModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTModificarActionPerformed
        PreparedStatement ps = null;
        try {
            Conexion conn= new Conexion();
            Connection con = conn.getConexion();
            String sql = "UPDATE alumno SET nombre='"+alu_TNombre.getText()+
                    "', ape_paterno='"+alu_TPapellido.getText()+"', "
                    + "ape_materno='"+alu_TSapellido.getText()+"', "
                    + "fechaNacimiento='"+alu_TNacimiento.getText()+"', "
                    + "direccion='"+alu_TDomicilio.getText()+"', telefono='"+
                    alu_TTelefono.getText()+"', correo='"+alu_TCorreo.getText()+"', "
                    + "semestre='"+alu_TSemestre.getText()+"' "
                            + "WHERE idAlumno="+alu_TClave.getText();
            ps=con.prepareStatement(sql);
            ps.execute();
            limpiarFields();
            JOptionPane.showMessageDialog(null, "Se han modificado los valores"
                    + " exitosamente.");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado,");
        }
    }//GEN-LAST:event_btnTModificarActionPerformed

    private void doc_ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_ClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_ClaveActionPerformed

    private void doc_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_NombreActionPerformed

    private void doc_PapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_PapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_PapellidoActionPerformed

    private void doc_SapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_SapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_SapellidoActionPerformed

    private void doc_DomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_DomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_DomicilioActionPerformed

    private void doc_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_TelefonoActionPerformed

    private void doc_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_CorreoActionPerformed

    private void btn_CanDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CanDocenteActionPerformed
        db.closeConnection();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CanDocenteActionPerformed

    private void btn_RegDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegDocenteActionPerformed
        SqlDocente modSql = new SqlDocente();
        Docente doc = new Docente();
        
        String pass = new String(doc_Password.getPassword());
        String passCon = new String(doc_Spassword.getPassword());
        
        if ("".equals(doc_Clave.getText()) ||"".equals(doc_Nombre.getText()) || 
            "".equals(doc_Papellido.getText()) || 
            "".equals(doc_Sapellido.getText()) ||
            "".equals(doc_Domicilio.getText()) || "".equals(doc_Telefono.getText()) || 
            "".equals(doc_Correo.getText()) || doc_Nacimiento.getDate()==null){
            JOptionPane.showMessageDialog(null, "Verifique que todos los campos"
                    + " esten correctos.");
        }else{
            if(pass.equals(passCon)){
                SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");

                String nuevoPass = MD5.getHash(pass);

                doc.setId(Integer.parseInt(doc_Clave.getText()));
                doc.setNombre(doc_Nombre.getText());
                doc.setApe_Paterno(doc_Papellido.getText());
                doc.setApe_Materno(doc_Sapellido.getText());
                doc.setFechaNacimiento(Date_Format.format(doc_Nacimiento.getDate()));
                doc.setDireccion(doc_Domicilio.getText());
                doc.setTelefono(doc_Telefono.getText());
                doc.setCorreo(doc_Correo.getText());
                doc.setContrasena(nuevoPass);
                if (modSql.registrar(doc)){
                    JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO");
                    limpiarFields();
                }else
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error, "
                            + "comprueba que los datos esten correctos.");
            }else{
                JOptionPane.showMessageDialog(null, "No coinciden las contraseñas");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegDocenteActionPerformed

    private void jtDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDocenteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocenteMouseClicked

    private void btn_ADocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ADocenteActionPerformed
        String campo = doc_TClave.getText();
                
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jtDocente.setModel(modelo);
            
            PreparedStatement ps;
            ResultSet rs;
            Conexion conn= new Conexion();
            Connection con = conn.getConexion();
            
            String sql ="SELECT idDocente, nombre, ape_paterno, ape_materno, "
                    +"fechaNacimiento, direccion, telefono, correo FROM Docente";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Clave");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Fecha de Nacimiento");
            modelo.addColumn("Dirección");
            modelo.addColumn("Teléfono");
            modelo.addColumn("Correo");
            
            int[] anchos = {40,90,90,90,80,100,50,70};
            for(int x=0; x< cantidadColumnas; x++)
                jtDocente.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0;i < cantidadColumnas; i++){
                    filas[i]= rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Se encontro un error y no es "
                    + "posible mostrar la información");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ADocenteActionPerformed

    private void doc_TCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_TCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_TCorreoActionPerformed

    private void btnTDBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTDBuscarActionPerformed

    private void btnTDModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTDModificarActionPerformed

    private void btnTDEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTDEliminarActionPerformed

    private void alu_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_NombreKeyTyped
        int limite_carac=25;
        if(alu_Nombre.getText().length()>limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 25 "
                    + "caracteres");
        }
    }//GEN-LAST:event_alu_NombreKeyTyped

    private void alu_ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_ClaveKeyTyped
        char c = evt.getKeyChar();
        int limite_carac=8;
        
        if (!(Character.isDigit(c) ||
            (c == evt.VK_BACK_SPACE) ||
            (c == evt.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(alu_Clave.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 8 "
                    + "dígitos");
        }
    }//GEN-LAST:event_alu_ClaveKeyTyped

    private void alu_TelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_TelKeyTyped
        char c = evt.getKeyChar();
        
        
        if (!(Character.isDigit(c) ||
            (c == evt.VK_BACK_SPACE) ||
            (c == evt.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        int limite_carac=10;
        if(alu_Tel.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 10"
                    + " dígitos");
        }
    }//GEN-LAST:event_alu_TelKeyTyped

    private void jB_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFields();
    }//GEN-LAST:event_jB_LimpiarActionPerformed

    private void alu_PapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_PapellidoKeyTyped
        int limite_carac=20;
        if(alu_Papellido.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 20 "
                    + "caracteres");
        }
    }//GEN-LAST:event_alu_PapellidoKeyTyped

    private void alu_SapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_SapellidoKeyTyped
        int limite_carac=20;
        if(alu_Sapellido.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 20 "
                    + "caracteres");
        }
    }//GEN-LAST:event_alu_SapellidoKeyTyped

    private void alu_DomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_DomicilioKeyTyped
        int limite_carac=30;
        if(alu_Domicilio.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 30"
                    + " caracteres");
        }
    }//GEN-LAST:event_alu_DomicilioKeyTyped

    private void alu_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_CorreoKeyTyped
        int limite_carac=30;
        if(alu_Correo.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 30"
                    + " caracteres");
        }
    }//GEN-LAST:event_alu_CorreoKeyTyped

    private void alu_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_PasswordKeyTyped
        
        
    }//GEN-LAST:event_alu_PasswordKeyTyped

    private void alu_SemestreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_SemestreKeyTyped
        char c = evt.getKeyChar();
        int limite_carac=2;
        
        if (!(Character.isDigit(c) ||
            (c == evt.VK_BACK_SPACE) ||
            (c == evt.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(alu_Semestre.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 2 "
                    + "dígitos");
        }
    }//GEN-LAST:event_alu_SemestreKeyTyped

    private void alu_TSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alu_TSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alu_TSemestreActionPerformed

    private void jB_Limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Limpiar1ActionPerformed
        limpiarFields();
        disableField();
    }//GEN-LAST:event_jB_Limpiar1ActionPerformed

    private void alu_TTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_TTelefonoKeyTyped
        char c = evt.getKeyChar();
        
        
        if (!(Character.isDigit(c) ||
            (c == evt.VK_BACK_SPACE) ||
            (c == evt.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        int limite_carac=10;
        if(alu_Tel.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 10"
                    + " dígitos");
        }
    }//GEN-LAST:event_alu_TTelefonoKeyTyped

    private void alu_TClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alu_TClaveKeyTyped
        char c = evt.getKeyChar();
        int limite_carac=8;
        
        if (!(Character.isDigit(c) ||
            (c == evt.VK_BACK_SPACE) ||
            (c == evt.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if(alu_Clave.getText().length()>=limite_carac){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar 8 "
                    + "dígitos");
        }
    }//GEN-LAST:event_alu_TClaveKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alu_Clave;
    private javax.swing.JTextField alu_Correo;
    private javax.swing.JTextField alu_Domicilio;
    private com.toedter.calendar.JDateChooser alu_Nacimiento;
    private javax.swing.JTextField alu_Nombre;
    private javax.swing.JTextField alu_Papellido;
    private javax.swing.JPasswordField alu_Password;
    private javax.swing.JTextField alu_Sapellido;
    private javax.swing.JTextField alu_Semestre;
    private javax.swing.JPasswordField alu_Spassword;
    private javax.swing.JTextField alu_TClave;
    private javax.swing.JTextField alu_TCorreo;
    private javax.swing.JTextField alu_TDomicilio;
    private javax.swing.JTextField alu_TNacimiento;
    private javax.swing.JTextField alu_TNombre;
    private javax.swing.JTextField alu_TPapellido;
    private javax.swing.JTextField alu_TSapellido;
    private javax.swing.JTextField alu_TSemestre;
    private javax.swing.JTextField alu_TTelefono;
    private javax.swing.JTextField alu_Tel;
    private javax.swing.JButton btnTBuscar;
    private javax.swing.JButton btnTDBuscar;
    private javax.swing.JButton btnTDEliminar;
    private javax.swing.JButton btnTDModificar;
    private javax.swing.JButton btnTEliminar;
    private javax.swing.JButton btnTModificar;
    private javax.swing.JButton btn_ADocente;
    private javax.swing.JButton btn_CanAlumno;
    private javax.swing.JButton btn_CanDocente;
    private javax.swing.JButton btn_RegAlumno;
    private javax.swing.JButton btn_RegDocente;
    private javax.swing.JTextField doc_Clave;
    private javax.swing.JTextField doc_Correo;
    private javax.swing.JTextField doc_Domicilio;
    private com.toedter.calendar.JDateChooser doc_Nacimiento;
    private javax.swing.JTextField doc_Nombre;
    private javax.swing.JTextField doc_Papellido;
    private javax.swing.JPasswordField doc_Password;
    private javax.swing.JTextField doc_Sapellido;
    private javax.swing.JPasswordField doc_Spassword;
    private javax.swing.JTextField doc_TClave;
    private javax.swing.JTextField doc_TCorreo;
    private javax.swing.JTextField doc_TDomicilio;
    private javax.swing.JTextField doc_TNacimiento;
    private javax.swing.JTextField doc_TNombre;
    private javax.swing.JTextField doc_TPapellido;
    private javax.swing.JTextField doc_TSapellido;
    private javax.swing.JTextField doc_TTelefono;
    private javax.swing.JTextField doc_Telefono;
    private javax.swing.JButton jB_Limpiar;
    private javax.swing.JButton jB_Limpiar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jf_logo;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTable jtDocente;
    private javax.swing.JLabel label_TClave;
    private javax.swing.JLabel label_TClave1;
    // End of variables declaration//GEN-END:variables
}
